### ISSUE TITLE
Allow Java extensions

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor-ant#29]
Enhancement: Could you incorporate the new Java extension points? Something like:
````
<asciidoctor:convert src ... >
  <blockprocessor classname="org.whatsit.MyBlockProcessor1"/>  
  <blockprocessor classname="org.whatsit.MyBlockProcessor2"/>
  <preprocessor classname="ChangeAttributeValuePreprocessor"/>
</asciidoctor:convert>
````

**Comment by binout** [comment]
Will be shipped in 1.5.2

The syntax is 
 <asciidoctor:convert sourceDirectory="src/asciidoc" outputDirectory="target" backend="html5">
        <inlineMacroProcessor blockName="twitter" className="org.asciidoctor.ant.extensions.TwitterMacro"/>
   </asciidoctor>
