### ISSUE TITLE
Upgrade to Asciidoctor 1.5.4

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor-ant#52]
Is this likely any time soon?

**Comment by binout** [comment]
I don't know if i release with just asciidoctorj alignment 
or I try to wrap asciidoctor-diagram, asciidoctor-epub in asciidoctor-ant 1.5.4, your opinion ?

**Comment by binout** [comment]
I will release a 1.5.4 with alignment on asciidoctorj 1.5.4.
I postpone the work on asciidoctor-diagram and epub integration.

**Comment by gsmet** [comment]
@binout just wanted to check that you're considering 1.5.4.1 and not 1.5.4?

**Comment by binout** [comment]
Yes asciidoctorj-1.5.4.1 and JRuby-1.7.25

**Comment by binout** [comment]
Release 1.5.4 done
